name: Windows

on:
  push:
    tags:
    - '*'

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master

      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Install Qt
        uses: ouuan/install-qt-action@v2.3.1

      - name: Build
        shell: powershell
        id: build
        run: |
          pushd "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools"
          cmd /c "VsMSBuildCmd.bat&set" |
          foreach {
            if ($_ -match "=") {
              $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
            }
          }
          popd
          Write-Host "Visual Studio 2017 Command Prompt variables set."
          $build_folder = "build"
          $release_folder = "Release"
          $ccx_ver = "${{ github.ref }}" -replace 'refs/tags/'
          $release_name = "ccx-desktop-win64-v$ccx_ver"
          $qt5_cmake = "${{ env.Qt5_Dir }}/lib/cmake" -replace '[/]', '\\'
          Write-Host "0"
          Write-Host "$qt5_cmake"
          # $qt5_bin = "${{ env.Qt5_Dir }}/bin"
          Remove-Item cryptonote -Recurse -ErrorAction Ignore
          git clone https://github.com/ConcealNetwork/conceal-core cryptonote
          dir
          $filecontent = Get-Content CMakeLists.txt
          $filecontent -replace '^set\(CMAKE_PREFIX_PATH.+',"set(CMAKE_PREFIX_PATH `"$($qt5_cmake)`")" | Set-Content CMakeLists.txt

          cat CMakeLists.txt
          New-Item "$build_folder" -ItemType Dir
          cd "$build_folder"
          # cd "$build_folder\$release_folder"

          # Start-Process xcopy -ArgumentList "${{ env.Qt5_Dir }}/bin/*.dll",".","/s","/y" -NoNewWindow -Wait
          # cp "${{ env.Qt5_Dir }}/bin/*.dll" .
          # cp -recurse "${{ env.Qt5_Dir }}/plugins/*" .
          # cp -recurse "${{ env.Qt5_Dir }}/qml/*" .

          dir
          # cd ..
          # dir

          Write-Host "1"
          Start-Process cmake -ArgumentList "-G ""Visual Studio 15 2017 Win64""",".." -NoNewWindow -Wait
          Write-Host "2"
          Start-Process msbuild -ArgumentList "CONCEAL-GUI.sln","/p:Configuration=Release" -NoNewWindow -Wait
          Write-Host "3"
          
          dir
          # Start-Process "$qt5_bin/windeployqt.exe" -ArgumentList "CONCEAL-GUI.exe" -NoNewWindow -Wait
          # dir

          Compress-Archive -Path *.exe -DestinationPath "$release_name.zip"
          $sha256 = (Get-FileHash "$release_name.zip").Hash
          $asset_path = "./$build_folder/$release_folder/$release_name.zip"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=ccx_ver::${ccx_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Conceal Desktop v${{ steps.build.outputs.ccx_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

