name: Windows

on:
  push:
    tags:
    - '*'

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@master

      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1

      - name: Install Qt
        uses: ouuan/install-qt-action@v2.3.1

      - name: Build
        shell: powershell
        id: build
        env:
          VCINSTALLDIR: ${{ env.VCINSTALLDIR }}
        run: |
          Write-Host "${{ env.VisualStudioVersion }}"
          Write-Host "${{ env.VS140COMNTOOLS }}"

          function Invoke-BatchFile
          {
              param([string]$Path, [string]$Parameters)

              $tempFile = [IO.Path]::GetTempFileName()

              ## Store the output of cmd.exe.  We also ask cmd.exe to output
              ## the environment table after the batch file completes
              cmd.exe /c " `"$Path`" $Parameters && set " > $tempFile

              ## Go through the environment variables in the temp file.
              ## For each of them, set the variable in our local environment.
              Get-Content $tempFile | Foreach-Object {
                  if ($_ -match "^(.*?)=(.*)$") {
                      Set-Content "env:\$($matches[1])" $matches[2]
                  }
                  else {
                      $_
                  }
              }

              Remove-Item $tempFile
          }
          $VcVars = 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsMSBuildCmd.bat'
          Invoke-BatchFile $VcVars
          
          Write-Host "Visual Studio 2017 Command Prompt variables set."
          Write-Host "${{ env.VS140COMNTOOLS }}"
          Write-Host "${{ env.VisualStudioVersion }}"

          $build_folder = "build"
          $release_folder = "Release"
          $ccx_ver = "${{ github.ref }}" -replace 'refs/tags/'
          $release_name = "ccx-desktop-win64-v$ccx_ver"
          $qt5_cmake = "${{ env.Qt5_Dir }}/lib/cmake" -replace '[/]', '\\'

          Remove-Item cryptonote -Recurse -ErrorAction Ignore
          git clone https://github.com/ConcealNetwork/conceal-core cryptonote

          $filecontent = Get-Content CMakeLists.txt
          $filecontent -replace '^set\(CMAKE_PREFIX_PATH.+',"set(CMAKE_PREFIX_PATH `"$($qt5_cmake)`")" | Set-Content CMakeLists.txt

          New-Item "$build_folder\$release_folder" -ItemType Directory

          Copy-Item "${{ env.Qt5_Dir }}/bin/*" $build_folder -Filter *.dll -Recurse
          Copy-Item "${{ env.Qt5_Dir }}/plugins/*" $build_folder -Recurse
          Copy-Item "${{ env.Qt5_Dir }}/qml/*" $build_folder -Recurse

          cd "$build_folder"
          Copy-Item "${{ env.Qt5_Dir }}/bin/*" $release_folder -Filter *.dll -Recurse
          Copy-Item "${{ env.Qt5_Dir }}/plugins/*" $release_folder -Recurse
          Copy-Item "${{ env.Qt5_Dir }}/qml/*" $release_folder -Recurse
          dir

          Start-Process cmake -ArgumentList "-G ""Visual Studio 15 2017 Win64""",".." -NoNewWindow -Wait
          Start-Process msbuild -ArgumentList "CONCEAL-GUI.sln","/p:Configuration=Release" -NoNewWindow -Wait
          
          dir "$release_folder"
          Start-Process "${{ env.Qt5_Dir }}/bin/windeployqt.exe" -ArgumentList "$release_folder/CONCEAL-GUI.exe" -NoNewWindow -Wait
          dir "$release_folder"

          Compress-Archive -Path "$release_folder/*.exe" -DestinationPath "$release_folder/$release_name.zip"
          $sha256 = (Get-FileHash "$release_folder/$release_name.zip").Hash
          $asset_path = "./$build_folder/$release_folder/$release_name.zip"
          echo "::set-output name=sha256::${sha256}"
          echo "::set-output name=release_name::${release_name}.zip"
          echo "::set-output name=asset_path::${asset_path}"
          echo "::set-output name=ccx_ver::${ccx_ver}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.build.outputs.asset_path }}
          name: Conceal Desktop v${{ steps.build.outputs.ccx_ver }}
          body: |
            **${{ steps.build.outputs.release_name }}**
            ${{ steps.build.outputs.sha256 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

